apiVersion: v1
kind: Service
metadata:
  name: bookreview-back
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: bookreview-back

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookreview-back
spec:
  selector:
    matchLabels:
      app: bookreview-back
  template:
    metadata:
      labels:
        app: bookreview-back
    spec:
      containers:
        - name: bookreview-back
          image: josemanuel117/bookreview-back-k8s
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5

