apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookreview-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookreview-front
  template:
    metadata:
      labels:
        app: bookreview-front
    spec:
      containers:
        - name: bookreview-front
          image: josemanuel117/bookreview-front:2.5
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"  # 250 milicores de CPU
            limits:
              cpu: "500m"  # 500 milicores de CPU
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5

